blueprint:
  name: CAP Alert Markdown Sensor
  description: Creates a sensor that formats CAP (Common Alerting Protocol) alerts as markdown for display in a markdown card
  domain: template
  input:
    alert_sensor:
      name: Alert Sensor
      description: The sensor entity that contains CAP-formatted alerts (e.g., from Norway Alerts, MetAlerts, or similar integrations)
      selector:
        entity:
          domain: sensor
    sensor_name:
      name: Sensor Name
      description: Name for the formatted sensor (will appear as sensor.{name})
      default: "cap_alerts_formatted"
      selector:
        text:
    show_icon:
      name: Show Alert Icons
      description: Display warning icons next to alert titles
      default: true
      selector:
        boolean:
    show_status:
      name: Show Status
      description: Show Expected/Ongoing/Ended status for each alert
      default: true
      selector:
        boolean:
    show_map:
      name: Show Maps
      description: Display map images if available
      default: true
      selector:
        boolean:

template:
  - sensor:
      - name: !input sensor_name
        unique_id: !input sensor_name
        state: "{{ state_attr('!input alert_sensor', 'active_alerts') | int(0) }}"
        attributes:
          formatted_content: >
            {% set sensor_entity = '!input alert_sensor' %}
            {% set alerts = state_attr(sensor_entity, 'alerts') %}
            {% set show_icon = !input show_icon %}
            {% set show_status = !input show_status %}
            {% set show_map = !input show_map %}
            
            {% if alerts and alerts | length > 0 %}
              {% for alert in alerts %}
                {% set start_ts = as_timestamp(alert.starttime) %}
                {% set end_ts = as_timestamp(alert.endtime) %}
                {% set now_ts = now().timestamp() %}
                
            ### {% if show_icon and alert.entity_picture %}<img src="{{ alert.entity_picture }}" width="32" style="vertical-align: middle;">{% endif %} {{ alert.title }}
                
            {% if show_status %}
            **Status**: {{ '⏰ Expected' if start_ts > now_ts else ('✅ Ended' if end_ts < now_ts else '⚠️ Ongoing') }}
            {% endif %}
                
            **Severity**: {{ alert.awareness_level_color | upper }}
                
            **Type**: {{ alert.event_awareness_name }}
                
            **Valid Period**: {{ start_ts | timestamp_custom('%B %d, %H:%M') }} to {{ end_ts | timestamp_custom('%B %d, %H:%M') }}
                
            #### Description
            {{ alert.description }}
                
            {% if alert.instruction %}
            #### Instructions
            {{ alert.instruction }}
            {% endif %}
                
            {% if alert.consequences %}
            #### Consequences
            {{ alert.consequences }}
            {% endif %}
                
            {% if alert.area %}
            **Area**: {{ alert.area }}
            {% endif %}
                
            **Certainty**: {{ alert.certainty }} | **Severity**: {{ alert.severity }}
            
            ---
                
            {% if show_map and alert.map_url %}
            <img src="{{ alert.map_url }}" width="400">
            {% endif %}
                
              {% endfor %}
            {% else %}
            No active alerts
            {% endif %}
